# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    ports:
      - "3000:3000" # phần này ta định nghĩa ở file .env nhé
    restart: always
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/mongo/
    depends_on:
      - mongo
volumes:
  mongodb: